base_url = "https://semanticdata.github.io/zola-guava/"
title = "Guava"
description = "A Zola theme without a real plan."

compile_sass = true
build_search_index = true
minify_html = false
generate_feed = true
feed_filename = "atom.xml"

author = "Miguel Pimentel"
taxonomies = [
  # { name = "categories", feed = true },
  # { name = "tags", feed = true },
]

[markdown]
highlight_code = true
smart_punctuation = true

[extra]
internalLinks = [
  { url = "blog", name = "Blog" },
  { url = "projects", name = "Projects" },
  { url = "test", name = "Test" },
]
